version: 2.1
jobs:
  build:
    docker:
      - image: gradle:7-jdk11
      - image: circleci/mongo:5.0.2-focal
        command: [mongod]
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew clean build -x test
      - run:
          name: Unit test
          command: ./gradlew test
      - run:
          name: Integration test
          command: ./gradlew integration
      - run:
          name: E2E test
          command: ./gradlew e2e
      - run:
          name: JaCoCo report
          command: ./gradlew jacocoTestReport
      - coverage-reporter/send_report:
          coverage-reports: 'build/reports/jacoco/test/jacocoTestReport.xml'
          skip: false

orbs:
  coverage-reporter: codacy/coverage-reporter@13.5.2